[package]
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
edition = "2018"
name = "futures-test-abort"
version = "0.1.0"

[dev-dependencies]
tokio = { version="0.2", features=["macros", "rt-core"] }